AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an S3 bucket with a name like "s3-tables-RANDOM_NUMBER"'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # 直接使用 !Sub 动态生成桶名（无需参数）
      BucketName: !Sub 's3-tables-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  BucketName:
    Description: 'Name of the created S3 bucket'
    Value: !Ref S3Bucket